---
title: "Outline"
author: "Madeline Gorchels"
date: "6/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1) At least two different functions that summarize climate data in some way (your choice - it could be finding a trend, or finding extremes; or even simply mean winter precipitation)

  - 

2) At least two functions that calculate some measure of impact (you can really make these us) -so for example you could create a function that computes a heat stress index based on air temperature with parameters that vary with for different species; or a function that estimates water supply from precipitation with parameters that vary to reflect water storage …you can make something up just as long as its somewhat sensible

3) One function that estimates the costs of impacts

4) Use multi-dimensional arrays in one of your functions

The package should contain:

some sample data
documentation for ALL functions
a vignette that shows how to use several of the functions with the sample data
3 separate tests - (next weeks lecture)

https://journals.ametsoc.org/doi/full/10.1175/WCAS-D-13-00002.1

https://www.nwf.org/-/media/Documents/PDFs/Press-Releases/Baseball_Fact-Sheet_07-11-18
